version: "3.1"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data
  backend:
    build:
      context: ./survey_sharing_backend
      dockerfile: Dockerfile
    container_name: springboot-backend
    restart: always
    ports: 
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/survey_sharing
  frontend:
    build:
      context: ./survey-sharing-frontend
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
volumes:
  data: {}